#!/usr/bin/env bash
# Install (or refresh) the launchd job that runs ops/backup.sh nightly at 02:30 —
# a missed run (laptop asleep) fires once on the next wake.
#
#   ops/install-backup.sh            install for this checkout
#   ops/install-backup.sh --print    show the generated plist without installing
#
# Remove later with:  launchctl bootout gui/$(id -u)/com.fettle.backup
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
LOG="$HOME/Library/Logs/fettle-backup.log"
PLIST_PATH="$HOME/Library/LaunchAgents/com.fettle.backup.plist"

plist() {
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Generated by ops/install-backup.sh for $REPO
  Snapshots backend/health.db to iCloud Drive (fettle-backups/), keeping 14 days.
  Runs through the backend venv python (like com.fettle.sync) — launchd denies
  /bin/bash TCC access to scripts under ~/Documents, but the venv binary is fine.
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.fettle.backup</string>
    <key>ProgramArguments</key>
    <array>
        <string>$REPO/backend/.venv/bin/python</string>
        <string>cli.py</string>
        <string>backup</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$REPO/backend</string>
    <key>StartCalendarInterval</key>
    <dict>
        <key>Hour</key>
        <integer>2</integer>
        <key>Minute</key>
        <integer>30</integer>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
</dict>
</plist>
EOF
}

if [ "${1:-}" = "--print" ]; then
  plist
  exit 0
fi

[ "$(uname)" = "Darwin" ] || { echo "launchd is macOS-only — use cron or a systemd timer elsewhere."; exit 1; }
[ -x "$REPO/backend/.venv/bin/python" ] || { echo "No backend venv yet — run ops/bootstrap.sh first."; exit 1; }

mkdir -p "$HOME/Library/LaunchAgents"
plist > "$PLIST_PATH"
launchctl bootout "gui/$(id -u)/com.fettle.backup" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH"

echo "Installed com.fettle.backup — snapshots nightly at 02:30."
echo "  dest      ~/Library/Mobile Documents/com~apple~CloudDocs/fettle-backups"
echo "  log       $LOG"
echo "  run now   launchctl kickstart gui/\$(id -u)/com.fettle.backup"
echo "  remove    launchctl bootout gui/\$(id -u)/com.fettle.backup"
