#!/usr/bin/env bash
# Install (or refresh) the launchd job that runs `cli.py sync` every 6 hours —
# each run also refreshes the daily briefing and sends any due notifications.
#
#   ops/install-sync.sh            install for this checkout
#   ops/install-sync.sh --print    show the generated plist without installing
#
# Remove later with:  launchctl bootout gui/$(id -u)/com.fettle.sync
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
LOG="$HOME/Library/Logs/fettle-sync.log"
PLIST_PATH="$HOME/Library/LaunchAgents/com.fettle.sync.plist"

plist() {
  cat <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!--
  Generated by ops/install-sync.sh for $REPO
  Exit 2 in the log means the 7-day token died — reconnect from the dashboard
  (or run: python cli.py auth).
-->
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.fettle.sync</string>
    <key>ProgramArguments</key>
    <array>
        <string>$REPO/backend/.venv/bin/python</string>
        <string>cli.py</string>
        <string>sync</string>
    </array>
    <key>WorkingDirectory</key>
    <string>$REPO/backend</string>
    <key>StartInterval</key>
    <integer>21600</integer>
    <key>RunAtLoad</key>
    <false/>
    <key>StandardOutPath</key>
    <string>$LOG</string>
    <key>StandardErrorPath</key>
    <string>$LOG</string>
</dict>
</plist>
EOF
}

if [ "${1:-}" = "--print" ]; then
  plist
  exit 0
fi

[ "$(uname)" = "Darwin" ] || { echo "launchd is macOS-only — use cron or a systemd timer elsewhere."; exit 1; }
[ -x "$REPO/backend/.venv/bin/python" ] || { echo "No backend venv yet — run ops/bootstrap.sh first."; exit 1; }

mkdir -p "$HOME/Library/LaunchAgents"
plist > "$PLIST_PATH"
launchctl bootout "gui/$(id -u)/com.fettle.sync" 2>/dev/null || true
launchctl bootstrap "gui/$(id -u)" "$PLIST_PATH"

echo "Installed com.fettle.sync — syncs every 6 hours."
echo "  log       $LOG"
echo "  run now   launchctl kickstart gui/$(id -u)/com.fettle.sync"
echo "  remove    launchctl bootout gui/$(id -u)/com.fettle.sync"
